<AboutApp>:
    name: 'about_app'

    MDFloatLayout:
        # bubbles bg
        Image:
            source: 'assets/Bubbles bg.png'
            allow_stretch: True
            size_hint: 1.5, 1.5
            pos_hint: {"center_x": .5, 'center_y': .4}

        # top menu
        MDTopAppBar:
            title: "About App"
            anchor_title: "left"
            elevation: 0
            md_bg_color: "#E79F48"
            left_action_items: [["arrow-left", lambda a: root.change_screen("right", "dashboard")]]
            pos_hint: {'top': 1}

        # contains all content
        MDFloatLayout:
            size_hint_max_x: 400
            pos_hint: {'center_x': 0.5}

            # title
            Image:
                source: "assets/Title.png"
                size_hint: 0.9, 0.75
                pos_hint: {'center_x': 0.515,'center_y': 0.794}

            Image:
                source: "assets/stuck.png"
                size_hint: 0.8, 0.8
                pos_hint: {'center_x': 0.5,'center_y': 0.67}

            # short summary
            MDScrollView:
                do_scroll_y: True
                do_scroll_x: False
                height: 147
                size_hint_y: None
                pos_hint: {"center_x": 0.5, "center_y": 0.49}

                MDBoxLayout:
                    orientation: "vertical"
                    size_hint_y: None
                    adaptive_height: True
                    pos_hint: {'center_x': 0.5,'center_y': 0.6}

                    MDLabel:
                        halign: 'center'
                        text:'This app provides a simple, easy, and fast note-taking experience; surely a great helper in doing lists and scribbling on-the-spot ideas.\n\n'
                        font_style: 'H1'
                        font_size: sp(20)
                        size_hint: .7, None
                        adaptive_height: True
                        pos_hint: {'center_x': 0.5,'center_y': 0.6}

                    MDLabel:
                        halign: 'center'
                        text: 'DEVELOPERS:\nAlba, Khent David \nLumbres, Luis Miguel\nRecio, Paolo Luigi\nRotap, Lilianne Claire\nTapia, Rachell Ann\nTemporal, Sebastian Audrey\nVirgines, Xein Deniel\n\nÂ©2022 GROUP 6 CS2-1N'
                        font_style: 'H1'
                        font_size: sp(15)
                        size_hint: .7, None
                        adaptive_height: True
                        pos_hint: {'center_x': 0.5,'center_y': 0.6}

            # bottom dino image
            Image:
                source: "assets/dino.png"
                size_hint: 0.85, 0.37
                pos_hint: {'center_x': 0.55,'center_y': 0.2}
